FROM   registry.access.redhat.com/ubi8/ubi:8.0

MAINTAINER   Red Hat Training <training@redhat.com>

# command line options to pass to the JVM
ENV	  JAVA_OPTIONS -Xmx512m
ENV       BIN_PATH /opt/app-root/bin

LABEL     io.openshift.tags java
LABEL     io.openshift.expose-services 8080:http


# Install the Java runtime, create a user for running the app, and set permissions
RUN   yum install -y --disableplugin=subscription-manager java-1.8.0-openjdk-headless && \
      yum clean all --disableplugin=subscription-manager -y && \
      mkdir -p $BIN_PATH

# Copy the runnable fat JAR to the container.
ADD   https://github.com/RedHatTraining/DO288-apps/releases/download/OCP-4.1-1/hello-java.jar $BIN_PATH/

COPY  run-app.sh $BIN_PATH/

RUN   chown -R root:root /opt/app-root && \
      chmod -R 770 /opt/app-root

EXPOSE 8080

USER  1001

# Run the fat JAR
CMD   $BIN_PATH/run-app.sh
